POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Ayush",
    "username": "ayushadmin",
    "email": "ayush@example.com",
    "password": "mysecretpassword",
    "role": "admin"
}

### Test Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "ayushadmin",
    "password": "mysecretpassword"
}

### Add Menu Item
POST http://localhost:3000/menu
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzksInJvbGUiOiJhZG1pbiIsImlhdCI6MTc5MDg0NzIzMiwiZXhwIjoxNzkwOTMzNjMyfQ.cjWTfVKC_QS_ioLtIzNg5s5NqLsktBR7c_E1QXQdQco
    "name": "Mo:Mo",
    "description": "Steamed dumplings filled with a savory mixture of vegetables or meat, served with a tangy dipping sauce.",
    "price": 10.00,
    "category": "Snacks", 
    "dietary_tags": "Both vegetarian and non-vegetarian options available, gluten-free, dairy-free"
}